language: java 
jdk: 
  - oraclejdk7 
  - openjdk7 
  - openjdk6 

before_install: "chmod 777 ./gradlew"
install: "java -cp ./gradle/wrapper/gradle-wrapper.jar org.gradle.wrapper.GradleWrapperMain assemble -i"
script: "./gradlew check -i"
