language: java 
jdk: 
  - oraclejdk7 
  - openjdk7 
  - openjdk6 

before_install: "chmod 777 ./gradlew"
install: 
  - "cd ./gradle/wrapper"
  - "java -cp ./gradle-wrapper.jar org.gradle.wrapper.GradleWrapperMain assemble -i"
  - "cd ../.."
script: "./gradlew check -i"
